<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Customer Transaction</title>

  <?php $this->load->view('css/style_create')?>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img class="animation__shake" src="<?=base_url('asstes/dist/img/loadingicon.png')?>" alt="icon loading" height="auto">
    </div>

    <!-- Navbar -->
    <?php $this->load->view('navbar')?>
    <!-- /.navbar -->
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="margin-left : auto">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-4 mt-4">
            <div class="col-sm-12">
              <h1 style="text-align: center;">Customer Detail</h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- SELECT2 EXAMPLE -->
          <div class="card card-default">
            <div class="card-header">
              <!-- /.card-header -->
              <form action="<?=site_url('transaksi/selectmenu')?>" method="post">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>ID User</label>
                      <input class="form-control" disabled="disabled" type="text" placeholder="Generated by system">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Status Paket</label>
                      <select class="form-control select2" name="status_paket" style="width: 100%;">
                        <?php if (!empty($this->session->userdata('status_paket'))) { ?>
                          <option value="<?=$this->session->userdata('status_paket')?>"><?=$this->session->userdata('status_paket')?></option>
                        <?php } ?>
                        <option>-- Pilih Status Paket --</option>
                        <option value="Regular">Regular</option>
                        <option value="Promotion">Promotion</option>
                        <option value="Hampers">Hampers</option>
                        <option value="Corporate">Corporate</option>
                        <option value="Staff Meals">Staff Meals</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>New/Existing Customer*</label>
                      <select class="form-control select2" style="width: 100%;">
                        <option selected="selected">New</option>
                        <option>Existing</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>ID Transaksi</label>
                      <input class="form-control" disabled="disabled" type="text" placeholder="Generated by system">
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Brand</label>
                      <select class="form-control select2" id="perusahaan" name="brand" style="width: 100%;">
                        <?php if (!empty($this->session->userdata('id_brand'))) { ?>
                          <?php if ($this->session->userdata('id_brand') == 1) { ?>
                            <option value="<?=$this->session->userdata('id_brand')?>">Dermaster</option>
                          <?php } else {?>
                            <option value="<?=$this->session->userdata('id_brand')?>">Derma Express</option>
                          <?php }?>
                        <?php } ?>
                        <option value="">-- Select Branch --</option>
                        <option value="1">Dermaster</option>
                        <option value="2">Derma Express</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Klinik</label>
                      <select class="form-control select2" name="id_klinik" id="klinik" style="width: 100%;">
                      <?php if (!empty($this->session->userdata('id_klinik'))) { ?>
                        <option value="<?=$this->session->userdata('id_klinik')?>"><?=$this->session->userdata('nama_klinik')?></option>
                      <?php } ?>
                      </select>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>ID Customer</label>
                      <?php if (!empty($this->session->userdata('id_cust'))) { ?>
                        <input class="form-control" name="id_customer" type="text" value="<?=$this->session->userdata('id_cust')?>">
                      <?php } else {?>
                        <input class="form-control" name="id_customer" type="text" placeholder="Generated by system">
                      <?php } ?>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Nama Customer</label>
                      <?php if (!empty($this->session->userdata('nama_cust'))) { ?>
                        <input class="form-control" name="nama_customer" id="nama_customer" type="text" value="<?=$this->session->userdata('nama_cust')?>">
                      <?php } else {?>
                        <input class="form-control" name="nama_customer" id="nama_customer" type="text" placeholder="">
                      <?php } ?>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Nomer Whatsapp<span style="color:red">*</span></label>
                      <?php if (!empty($this->session->userdata('telp_1'))) { ?>
                        <input class="form-control" name="telp_1" maxlength="13" onkeypress="return hanyaAngka(event)" type="text" value="<?=$this->session->userdata('telp_1')?>">
                      <?php } else {?>
                        <input class="form-control" name="telp_1" maxlength="13" onkeypress="return hanyaAngka(event)" type="text" placeholder="">
                      <?php } ?>
                      <!-- <input class="form-control" type="text" name="telp_1" maxlength="13" onkeypress="return hanyaAngka(event)" placeholder=""> -->
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Nomer Telephone</label>
                      <?php if (!empty($this->session->userdata('telp_2'))) { ?>
                        <input class="form-control" name="telp_2" maxlength="13" onkeypress="return hanyaAngka(event)" type="text" value="<?=$this->session->userdata('telp_2')?>">
                      <?php } else {?>
                        <input class="form-control" name="telp_2" maxlength="13" onkeypress="return hanyaAngka(event)" type="text" placeholder="">
                      <?php } ?>
                      <!-- <input class="form-control" type="text" name="telp_2" maxlength="13" onkeypress="return hanyaAngka(event)" placeholder=""> -->
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Tanggal Transaksi</label>
                      <div class="input-group date" id="reservationdate" data-target-input="nearest">
                        <?php if (!empty($this->session->userdata('tgl_trans'))) { ?>
                          <input type="text" name="tgl_trans" class="form-control datetimepicker-input" data-target="#reservationdate" value="<?=$this->session->userdata('tgl_trans')?>" />
                          <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        <?php } else {?>
                          <input type="text" name="tgl_trans" class="form-control datetimepicker-input" data-target="#reservationdate" />
                          <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        <?php } ?>
                      </div>
                    </div>
                    <!-- /.form-group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Waktu Transaksi</label>
                      <div class="input-group date" id="timepicker" data-target-input="nearest">
                        <?php if (!empty($this->session->userdata('waktu_trans'))) { ?>
                          <input type="text" name="waktu_trans" class="form-control datetimepicker-input" data-target="#timepicker" value="<?=$this->session->userdata('waktu_trans')?>" />
                          <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                          </div>
                        <?php } else {?>
                          <input type="text" name="waktu_trans" class="form-control datetimepicker-input" data-target="#timepicker" />
                          <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                          </div>
                        <?php } ?>
                      </div>
                    </div>
                  </div>
                </div>
                
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Tanggal Pembayaran</label>
                      <div class="input-group date" id="reservationdate2" data-target-input="nearest">
                        <?php if (!empty($this->session->userdata('tgl_pembayaran'))) { ?>
                          <input type="text" name="tgl_pembayaran" class="form-control datetimepicker-input" data-target="#reservationdate2" value="<?=$this->session->userdata('tgl_pembayaran')?>" />
                          <div class="input-group-append" data-target="#reservationdate2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        <?php } else {?>
                          <input type="text" name="tgl_pembayaran" class="form-control datetimepicker-input" data-target="#reservationdate2" />
                          <div class="input-group-append" data-target="#reservationdate2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                          </div>
                        <?php } ?>
                      </div>
                    </div>
                    <!-- /.form-group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Waktu Pembayaran</label>
                      <div class="input-group date" id="timepicker2" data-target-input="nearest">
                        <?php if (!empty($this->session->userdata('waktu_pembayaran'))) { ?>
                          <input type="text" name="waktu_pembayaran" class="form-control datetimepicker-input" data-target="#timepicker2" value="<?=$this->session->userdata('waktu_trans')?>"  />
                          <div class="input-group-append" data-target="#timepicker2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                          </div>
                        <?php } else {?>
                          <input type="text" name="waktu_pembayaran" class="form-control datetimepicker-input" data-target="#timepicker2" />
                          <div class="input-group-append" data-target="#timepicker2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="far fa-clock"></i></div>
                          </div>
                        <?php } ?>
                        
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Status Pembayaran</label>
                      <div class="input-group date" id="reservationdate" data-target-input="nearest">
                        <input type="text" class="form-control" name="status_pembayaran" readonly value="Lunas">
                        <!-- <select class="form-control select2" style="width: 100%;">
                          <option selected="selected"></option>
                          <option>Lunas</option>
                        </select> -->
                        <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                        </div>
                      </div>
                    </div>
                    <!-- /.form-group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Status Verifikasi</label>
                      <div class="input-group date" id="timepicker" data-target-input="nearest">
                        <input type="text" name="status_verifikasi" id="" class="form-control" value="Not Verified" readonly>
                        <!-- <select class="form-control select2" style="width: 100%;">
                          <option selected="selected"></option>
                          <option>Not Yet Verified</option>
                        </select> -->
                        <div class="input-group-append" data-target="#timepicker" data-toggle="datetimepicker">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Qty Total</label>
                      <input class="form-control" type="text" readonly name="qty_total" value="<?=$qty_total?>" placeholder="Pack..">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Remarks</label>
                      <input class="form-control" name="remarks" type="text" placeholder="">
                    </div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">Detail Transaksi</h3>
                    </div>
                    <div class="row">
                      <div class="col-12">
                        <div class="button-create">
                          <button type="submit" class="btn btn-primary" title="Add" style="margin-top: 10px;"> <i class="fas fa-plus">
                            </i>
                          </button>
                          <!-- <a href="<?=site_url('transaksi/selectmenu')?>" id="datacust" class="btn btn-primary" title="Add" role="button" style="margin-top: 10px;"><i class="fas fa-plus"></i></a> -->
                        </div>
                      </div>
                    </div>
                    </form>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <table class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <th>ID Transaksi</th>
                            <th>Kategori Paket</th>
                            <th>Jenis Paket</th>
                            <th>Waktu Paket</th>
                            <th>Qty Paket</th>
                            <th>Periode Paket</th>
                            <th>Detail Paket</th>
                            <!-- <th>Status Pembayaran</th> -->
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php if (empty($cart)) { ?>
                            <tr>
                              <td colspan="8"><i> Tidak Ada Data</i></td>
                            </tr>
                          <?php }
                          foreach ($cart as $key) {?>
                            <tr>
                            <td><?=$key['id']?></td>
                            <td><?=$key['kategori_paket']?></td>
                            <td><?=$key['jenis_paket']?></td>
                            <td><?=$key['waktu_paket']?></td>
                            <td><?=$key['qty_paket']?></td>
                            <td><?=$key['periode_paket']?></td>
                            <td><?=$key['detail_paket']?></td>
                            <!-- <td> Lunas</td> -->
                            <td>
                              <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-info" data-toggle="tooltip" title="View"><i
                                    class="fas fa-eye"></i></a>
                                <a href="#" class="btn btn-warning" data-toggle="tooltip" title="Create"><i
                                    class="fas fa-pencil-alt"></i></a>
                                <a href="<?=site_url('transaksi/removefromcart/'.$key['rowid'])?>" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                    class="fas fa-trash"></i></a>
                              </div>
                          </tr>
                          <?php } ?>
                        </tbody>
                      </table>
              <hr>
              <!-- stop delivery form -->
              <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">Stop Delivery</h3>
                    </div>
                    <div class="row">
                      <div class="col-12">
                        <div class="button-create">
                          <a class="btn btn-primary" data-toggle="tooltip" title="Add" href="stop-delivery.html" role="button"
                            style="margin-top: 10px;"> <i class="fas fa-plus">
                            </i>
                          </a>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <table class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <th>ID Transaksi</th>
                            <th>Start Hold</th>
                            <th>End Hold Delivery</th>
                            <th>Start Delivery</th>
                            <th>Keterangan</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td colspan="6"><i> Tidak Ada Data</i></td>
                          </tr>
                          <!-- <tr>
                            <td>Del001</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>Isi keterangan</td>
                            <td>
                              <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-info" data-toggle="tooltip" title="View"><i
                                    class="fas fa-eye"></i></a>
                                <a href="#" class="btn btn-warning" data-toggle="tooltip" title="Create"><i
                                    class="fas fa-pencil-alt"></i></a>
                                <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                    class="fas fa-trash"></i></a>
                              </div>
                          </tr>
                          <tr>
                            <td>Del001</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>dd/mm/yyyy</td>
                            <td>Isi keterangan</td>
                            <td>
                              <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-info" data-toggle="tooltip" title="View"><i
                                    class="fas fa-eye"></i></a>
                                <a href="#" class="btn btn-warning" data-toggle="tooltip" title="Create"><i
                                    class="fas fa-pencil-alt"></i></a>
                                <a href="#" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i
                                    class="fas fa-trash"></i></a>
                              </div>
                            </td>
                          </tr> -->
                        </tbody>
                      </table>
                    </div>
                  </div> <!-- div close tabel stop delivery -->
                  <hr>
                  <div class="row">
                    <div class="col-12">
                      <div class="btn btn-group pull-right">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="btn btn-group">
                              <a href="customer-transaction.html"><button type="button" class="btn btn-warning">Back</button></a>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="btn btn-group">
                            <a href="<?=site_url('transaksi/insert_trans')?>" type="button" class="btn btn-success">Save</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- </form> -->
            </div>
          </div>
        </div> <!-- close div container fluid -->



        <!-- /.modal detail paket-->
        <div class="modal fade" id="modal-lg">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Create Detail Transaksi</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>ID Transaksi</label>
                        <input class="form-control" disabled="disabled" type="text" placeholder="Generated by system">
                        </select>
                      </div>
                      <div class="form-group">
                        <label>Kategori Paket</label>
                        <select class="form-control select2" style="width: 100%;">
                          <option selected="selected">Healthy A</option>
                          <option>Healthy B</option>
                          <option>Healthy C</option>
                        </select>
                      </div>
                      <!-- /.form-group -->
                      <div class="form-group">
                        <label>Jenis Paket</label>
                        <select class="form-control select2" style="width: 100%;">
                          <option selected="selected">Healthy</option>
                          <option>Slimming</option>
                          <option>Other</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <label>Waktu Paket</label>
                        <select class="form-control select2" style="width: 100%;">
                          <option selected="selected">Lunch</option>
                          <option>Dinner</option>
                          <option>Lunch - Dinner</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <label>Qty Paket</label>
                        <input class="form-control" type="text" placeholder="Pack..">
                      </div>
                      <div class="form-group">
                        <label>Periode Paket</label>
                        <select class="form-control select2" style="width: 100%;">
                          <option selected="selected">2 Minggu</option>
                          <option>1 Bulan</option>
                          <option>2 Bulan</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <label>Detail Paket</label>
                        <input class="form-control" type="text" placeholder="Detail paket yang dipesan">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success">Save</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.close div modal detail transaksi -->
      </section>
     
    <?php $this->load->view('footer')?>
    <?php $this->load->view('js/script_create')?>
    
    <script>
  		function hanyaAngka(evt) {
  		  var charCode = (evt.which) ? evt.which : event.keyCode
  		   if (charCode > 31 && (charCode < 48 || charCode > 57))

  		    return false;
  		  return true;
  		}
  	</script>

    <script>
      // var form = document.getElementById("user");
      // document.getElementById("datacust").addEventListener("click", function () {
      //   console.log(form.submit());
      //   // form.submit();
      // });

    </script>
    <script>
      $(document).ready(function(){
        $('#perusahaan').change(function(){
          var perusahaan = $(this).val();
          $.ajax({
            type: "POST",
            url: "<?=site_url('transaksi/getklinik')?>",
            data: {
              perusahaan:perusahaan
            },
            success : function(response){
              // alert(response);
              $('#klinik').html(response);
              $('#klinik').selectpicker('refresh');
            }
          })
        })
      })
    </script>

    <!-- <script>
      $('#passing-datacust').click(function(){
        var val = $(this).attr('class');
        var val2 = $("#nama_customer").val();
        alert(val2);
        document.getElementById("cust").submit();
      });
    </script> -->
</body>
</html>
